users = 
  getAll: (req, res) ->
    allusers = data
    # Spoof a DB call
    res.json allusers
    return
  getOne: (req, res) ->
    id = req.params.id
    user = data[0]
    # Spoof a DB call
    res.json user
    return
  create: (req, res) ->
    newuser = req.body
    data.push newuser
    # Spoof a DB call
    res.json newuser
    return
  update: (req, res) ->
    updateuser = req.body
    id = req.params.id
    data[id] = updateuser
    # Spoof a DB call
    res.json updateuser
    return
  delete: (req, res) ->
    id = req.params.id
    data.splice id, 1
    # Spoof a DB call
    res.json true
    return
data = [
  {
    name: 'user 1'
    id: '1'
  }
  {
    name: 'user 2'
    id: '2'
  }
  {
    name: 'user 3'
    id: '3'
  }
]
module.exports = users

# ---
# generated by js2coffee 2.1.0