platform :ios, '9.0'
use_frameworks!

target 'Grapevine' do
    pod 'Alamofire', '~> 3.3'
    pod 'ObjectMapper', '~> 1.2'
    pod 'AlamofireObjectMapper', '~> 3.0'
    pod 'CVCalendar', '~> 1.2.7'
end
