platform :ios, '8.0'
use_frameworks!

target 'Grapevine' do
    pod 'Alamofire', '~> 2.0'
    pod 'ObjectMapper', '~> 0.17'
    pod 'AlamofireObjectMapper', '~> 1.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'CVCalendar', '~> 1.2.7'
end
